### ISSUE TITLE
failed to download gpg key

### ISSUE THREAD

**Issue by brettswift** [voxpupuli/puppet-rvm#118] opened 2016-03-10 13:51 UTC
I have the output of the error below,  module versions used,  and a workaround at the bottom.

This is on CentOS 6.4  and RHEL 6.4. 

Should this work out of the box?

```
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.11.tgz' - 'https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc'!
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: try downloading the signatures:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:     sudo gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: or if it fails:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:     command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: the key can be compared with:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:     https://rvm.io/mpapis.asc
==> tca: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns:     https://keybase.io/mpapis
==> tca: Error: /usr/bin/curl -fsSL https://get.rvm.io | bash -s -- --version latest returned 2 instead of one of [0]
==> tca: Error: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: change from notrun to 0 failed: /usr/bin/curl -fsSL https://get.rvm.io | bash -s -- --version latest returned 2 instead of one of [0]
```

Modules included:

```
mod 'gnupg',
    :git => 'git://github.com/n1tr0g/golja-gnupg.git',
    :ref => '67da08a' #When tagged: '1.2.3'
mod 'rvm',
    :git => 'git://github.com/maestrodev/puppet-rvm.git',
    :ref => 'v1.12.1'
```

```
exec { 'import_gpg_key':
  command => 'curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -',
  unless  => 'gpg --fingerprint | grep RVM',
}

class { '::rvm':
  gnupg_key_id => false
}

Exec['import_gpg_key'] ->
Class['rvm']

```

**Comment by cyberious** [comment] 2016-03-21 22:58
Bit me as well

**Comment by rubys** [comment] 2016-04-25 00:27
I'm seeing this too... on Ubuntu 16.04.

Two comments:

* On puppet 3.8.5, I need to add `path => '/usr/bin:/bin'` to `Exec[import_gpg_key]`.
* The workaround works for me, but *only* if I start from scratch.  Otherwise `gpg --fingerprint | grep RVM` succeeds and the import is not run.  Running the `curl...-import -` command outside of puppet and then rerunning puppet succeeds.  The output from `gpg --fingerprint`, however, is not changed by the running of the import command manually.

**Comment by joshuaspence** [comment] 2016-04-25 23:38
Yep, I also hit this issue.

**Comment by Mirceaa** [comment] 2016-08-18 06:50
Me too, on Ubuntu 14.04

**Comment by Hoodoo** [comment] 2016-11-30 11:26
I've hit this one, too. I looked into gpg module code:

`  def add_key_from_key_server
    command = "gpg --keyserver #{resource[:key_server]} --recv-keys #{resource[:key_id]}"
    begin
      output = Puppet::Util::Execution.execute(command,  :uid => user_id, :failonfail => true)
    rescue Puppet::ExecutionFailure => e
      raise Puppet::Error, "Key #{resource[:key_id]} does not exist on #{resource[:key_server]}"
    end
end`

ANY error results in printing that error message, it's plain deceptive.

I've change it to

`  def add_key_from_key_server
    command = "gpg -v --homedir /root --keyserver #{resource[:key_server]} --recv-keys #{resource[:key_id]}"
    Puppet::Util::Execution.execute(command, :failonfail => true, :combine => true)
  end
` 
in order to see what's _really_ happening.

Anyway, since it would install key each puppet run as it is, I decided to get rid of it and go with one extra exec to install the key as needed.

I also noticed that the rvm module does not call for gnupg and it relies on the script to do that, I'm currently working on fixing that, I can't download a script and trust it to call for verification.

**Comment by ekohl** [comment] 2022-07-06 13:52
I'm going to close this based on its age. If you can still reproduce it, please reopen.

**Closed by ekohl** 2022-07-06 13:52 UTC
