### ISSUE TITLE
After installing several rubies with bundler for each, bundler is not available when entering project directory

### ISSUE THREAD

**Issue by jasonrobertfox** [voxpupuli/puppet-rvm#88] opened 2015-04-08 16:47 UTC
Trying to sort the problem I'm detailing here: http://stackoverflow.com/questions/29520563/why-does-bundler-disapear-after-entering-project-directory-with-puppet-installed

I'm not sure if it is related to my ignorance of something in set up (likely) or a possible bug with this install module. I want to install a few rubies and have bundler installed for each, here is the relevant part of my `main.pp`:

```
# Install and Setup RVM
class { 'rvm': }
rvm::system_user { vagrant: ; root: ; }

rvm_system_ruby {
  'ruby-2.0.0':
    ensure      => 'present',
    default_use => false;
  'ruby-2.1.5':
    ensure      => 'present',
    default_use => false;
  'ruby-2.2.1':
    ensure      => 'present',
    default_use => true;
}

rvm_gem {
  'bundler-2.0.0':
    name         => 'bundler',
    ruby_version => 'ruby-2.0.0',
    ensure       => latest,
    require      => Rvm_system_ruby['ruby-2.0.0'];
}

rvm_gem {
  'bundler-2.1.5':
    name         => 'bundler',
    ruby_version => 'ruby-2.1.5',
    ensure       => latest,
    require      => Rvm_system_ruby['ruby-2.1.5'];
}

rvm_gem {
  'bundler-2.2.1':
    name         => 'bundler',
    ruby_version => 'ruby-2.2.1',
    ensure       => latest,
    require      => Rvm_system_ruby['ruby-2.2.1'];
}
```

when i cd into a project directory that specifies `2.1.5` in the `.ruby-version` file, bundler is not available.

Please help. Thanks! All the source is here: https://github.com/neverstopbuilding/talon

**Comment by TJM** [comment] 2015-04-08 17:20
Gonna offer a quick (shooting from the hip) response... because I have been bit by something like this before :)

Did you logout and login after applying the puppet manifest to ensure that you had the "special sauce" that RVM installs in the user's environment?

You can verify by doing `ruby -v`  or `rvm info` before `which bundler` ;)

~tommy

**Comment by jasonrobertfox** [comment] 2015-04-08 17:29
After a fresh provision, this uses the default, latest ruby:

```
: vagrant ssh
~
: ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
~
: rvm info

ruby-2.2.1:

  system:
    uname:       "Linux talon 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "ubuntu/14.04/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 5.0.2 (x86_64-pc-linux-gnu)"

  rvm:
    version:      "rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "18 hours 2 minutes 59 seconds ago"
    path:         "/usr/local/rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.2.1p85"
    date:         "2015-02-26"
    platform:     "x86_64-linux"
    patchlevel:   "2015-02-26 revision 49769"
    full_version: "ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.2.1"
    ruby:         "/usr/local/rvm/rubies/ruby-2.2.1"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.2.1/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.2.1/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.2.1/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-2.2.1/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.2.1/bin:/usr/local/rvm/gems/ruby-2.2.1@global/bin:/usr/local/rvm/rubies/ruby-2.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin:/home/vagrant/bin:/usr/local/bin:"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.2.1"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.2.1:/usr/local/rvm/gems/ruby-2.2.1@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.2.1"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.2.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

And then going into the project folder and running the same: 

```
: cd /vagrant/home/clients/my_client/my_project
/vagrant/home/clients/my_client/my_project (master)
: ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
/vagrant/home/clients/my_client/my_project (master)
: rvm info

ruby-2.1.5@my_project:

  system:
    uname:       "Linux talon 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "ubuntu/14.04/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 5.0.2 (x86_64-pc-linux-gnu)"

  rvm:
    version:      "rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "18 hours 4 minutes 32 seconds ago"
    path:         "/usr/local/rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.1.5p273"
    date:         "2014-11-13"
    platform:     "x86_64-linux"
    patchlevel:   "2014-11-13 revision 48405"
    full_version: "ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.1.5@my_project"
    ruby:         "/usr/local/rvm/rubies/ruby-2.1.5"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.1.5/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.1.5/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-2.1.5/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.1.5@my_project/bin:/usr/local/rvm/gems/ruby-2.1.5@global/bin:/usr/local/rvm/rubies/ruby-2.1.5/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/bin:/usr/local/bin:"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.1.5@my_project"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.1.5@my_project:/usr/local/rvm/gems/ruby-2.1.5@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.1.5"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.1.5/.irbrc"
    RUBYOPT:      ""
    gemset:       "my_project"
```

**Comment by nmccready** [comment] 2015-08-06 22:51
I have a similar problem where my app needs `foreman` installed prior to running.

```
Exec {
    path => [ "/bin/", "/sbin/" , "/usr/bin/", "/usr/sbin/" ]
}

group { "puppet":
    ensure => "present",
}

$node_version = '0.12.6'
$ruby_version = 'ruby-2.1.3'

include update
include stdlib
include '::gnupg'
include nginx

#RVM
rvm_system_ruby {
  $ruby_version:
    ensure      => 'present',
    default_use => true;
}->
rvm_gem {
  'foreman':
    name         => 'foreman',
    ruby_version => $ruby_version,
    ensure       => latest,
    require      => Rvm_system_ruby[$ruby_version];
}->
class { 'nvm_nodejs':#NODE
  user    => 'vagrant',
  version => '0.12.6',
  npm_version => '2.12.1'
}->
class { 'rvm':
  system_users => ['www-data','vagrant'], }->
class { 'app':#RUN  APP
  user    => 'vagrant',
  node_version => $node_version,
  ruby_version =>  $ruby_version
}

```

This does install everything; however I want the app running on the first boot via `vagrant up` the app does run fine on `vagrant provision`. Where the app runs `foreman run someScript`. My guess is I am going to have to make a service in init.d to over come this.

**Comment by carlossg** [comment] 2015-09-23 17:37
@jasonrobertfox is it because you are using a gemset (`@my_project`) and not the global 2.1.5 ?

try

```
rvm 2.1.5 do bundle --version
rvm 2.2.1 do bundle --version
rvm 2.1.5@my_project do bundle --version
```

**Comment by andrewfraley** [comment] 2016-12-13 16:40
I have a similar issue where I install bundler through rvm_gem, but bundle isn't available until the next Puppet run.  Is there some trick to where I can actually use the bundle command during the same Puppet run?

**Comment by bhops** [comment] 2017-05-26 21:30
@andrewfraley Did you ever find a solution to this?

**Comment by andrewfraley** [comment] 2017-05-26 21:48
@bhops I spent a good 20 hours on trying to find an elegant solution, I never did.

**Comment by ekohl** [comment] 2022-07-06 13:55
I'm going to close this based on its age. If you can still reproduce it, please reopen.

**Closed by ekohl** 2022-07-06 13:55 UTC
